server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders: "*"
      routes:
        - id: USER-AUTH-SERVICE
          predicates:
            - Path=/users/**
          uri: lb://USER-SERVICE

        - id: BUG-SERVICE
          predicates:
            - Path=/bugs/**
          uri: lb://BUG-SERVICE

        - id: PROJECT-SERVICE
          predicates:
            - Path=/projects/**
          uri: lb://PROJECT-SERVICE

        - id: NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          uri: lb://NOTIFICATION-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
