package com.example.Bug.Service.Entity;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Bug {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @NotBlank(message = "Enter the bug title")
    @Column(name = "title")
    private String title;

    @Column(name = "description", length = 1000)
    private String description;

    @Column(name = "priority")// HIGH, LOW, MEDIUM
    @Enumerated(EnumType.STRING)
    private BugPriority priority;
    // the bug with project

    @Column(name = "projectName")
    private String projectName; //reference to the project

    @Enumerated(EnumType.STRING)
    @Column(name = "BugStatus")
    private BugStatus status;

    @Column(name = "Bug_customer_id")
    private Long customerId;

    @Column(name = "assignedStaffId")
    private Long assignedStaffId;

    // customer sends only (title , description, priority, projectId)
    // status, customerID, assignedStaffId , Id --> autogenerated
}
